# Generated by Django 4.0.3 on 2022-03-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_procedure_master_procedure_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.ImageField(upload_to='foto/'),
        ),
    ]
